/**
 * This class is generated by jOOQ
 */
package cxf.sample.persistence.schema;


import cxf.sample.persistence.schema.tables.Person;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CxfSample extends SchemaImpl {

	private static final long serialVersionUID = 497826689;

	/**
	 * The reference instance of <code>cxf_sample</code>
	 */
	public static final CxfSample CXF_SAMPLE = new CxfSample();

	/**
	 * No further instances allowed
	 */
	private CxfSample() {
		super("cxf_sample");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Person.PERSON);
	}
}
