/**
 * This class is generated by jOOQ
 */
package cxf.sample.persistence.schema;


import cxf.sample.persistence.schema.tables.Person;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cxf_sample
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cxf_sample.person
	 */
	public static final Person PERSON = cxf.sample.persistence.schema.tables.Person.PERSON;
}
